version: "3.7"

services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - cassandra_data:/var/lib/cassandra/data
    networks:
      - Hive

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.11.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
    networks:
      - Hive
  
  cortex:
    container_name: cortex
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    environment:
      - 'JOB_DIRECTORY=/opt/cortex/jobs'
    ports:
      - '0.0.0.0:9001:9001'
    volumes:
      - cortex_conf:/etc/cortex
      - cortex_logs:/var/log/cortex
      - cortex_tmp:/tmp
      #- ./cortex/Cortex-Analyzers:/opt/cortex/analyzers
      #- .cortex/Cortex-Analyzers/analyzers.json:/opt/cortex/analyzers/analyzers.json
    privileged: true
    networks:
      - Hive
  
  thehive:
    container_name: thehive
    image: 'thehiveproject/thehive4:latest'
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - '0.0.0.0:9210:9000'
    volumes:
      - thehive_conf:/etc/thehive
      - thehive_data:/opt/thp/thehive/data
      - thehive_index:/opt/thp/thehive/index
    command:
      --cortex-port 9001
      --cortex-keys ${CORTEX_KEY}
    networks:
      - Hive
      
networks:
    Hive:
        driver: bridge

volumes:
  cassandra_data:
  elasticsearch_data:
  elasticsearch_logs:
  cortex_conf:
  cortex_logs:
  cortex_tmp:
  thehive_conf:
  thehive_data:
  thehive_index:
